comment = "Reason: fast"
num =>
  (if (eql num 0) "0"
  (if (eql num 1) "1"
  (if (eql num 2) "2"
  (if (eql num 3) "3"
  (if (eql num 4) "4"
  (if (eql num 5) "5"
  (if (eql num 6) "6"
  (if (eql num 7) "7"
  (if (eql num 8) "8"
  (if (eql num 9) "9"
  (if (eql num 10) "a"
  (if (eql num 11) "b"
  (if (eql num 12) "c"
  (if (eql num 13) "d"
  (if (eql num 14) "e"
  (if (eql num 15) "f"
  "0"))))))))))))))))
